// Menanamkan prompt generasi ke dalam PNG comp (provenance).
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const EMBED = 'C:\\Users\\ufeek\\.qoder\\skills\\impeccable\\scripts\\embed-prompt.mjs';
const dir = path.resolve('.impeccable/mocks');

const prompts = {
  'comp-1-buku-kas.png': `Flat high-fidelity mobile app UI screenshot, portrait phone viewport, NO device frame, NO poster atmosphere. This is the home screen ("Beranda") of an Indonesian batik shop stock-ledger app named "Aninda Payu", designed as a shop ledger book (buku kas). Structure top to bottom: (1) ledger header band on bone paper #F4F1E9: shop name "Aninda Payu" in bold condensed grotesque display type (Bricolage Grotesque style) in deep blue-black ink #1C2B36, thin double rule under it like a ledger heading, small date line "Sabtu, 22 Agu 2026" in body sans (Public Sans style); (2) a ruled summary table with pale blue horizontal ruling lines #B9CFDF like notebook rules, three rows: "Stok berjalan" value "128 pcs", "Nilai stok (modal)" value "Rp 9.450.000", "Penjualan hari ini" value "Rp 1.250.000", values right-aligned in tabular numerals, grand total row underlined twice in red pencil #B3372B; (3) section "Aksi cepat" as an index list of four full-width ruled rows, each row: action name left ("Catat Penjualan", "Stok Masuk", "Stock Opname", "Laporan") and a small hand-drawn arrow right, rows separated by blue rules, no cards, no icons; (4) section "Stok menipis" with two entries written in red pencil color #B3372B: "Kemeja Malaman M01 — 2 pcs", "Batik Colet C03 — 0 pcs"; (5) fixed bottom navigation bar on paper with a single blue rule on top: five text items "Stok Transaksi Opname Laporan Pengaturan", active item in indigo #24518E with a short soga-brown #9C4A1F underline stroke. Entire surface flat: zero drop shadows, zero gradients, zero glass, 2px corner radius, 1px borders #D8D2C4, generous whitespace, crisp vector UI, legible Indonesian text, realistic app screenshot not illustration.`,
  'comp-2-harian.png': `Flat high-fidelity mobile app UI screenshot, portrait phone viewport, NO device frame. Home screen ("Beranda") of Indonesian batik shop stock-ledger app "Aninda Payu", visual world of a shop ledger book (buku kas): bone paper background #F4F1E9, deep blue-black ink text #1C2B36, pale blue notebook ruling lines #B9CFDF, indigo #24518E for primary actions, soga brown #9C4A1F tiny accents, red pencil #B3372B for negatives. Structure top to bottom: (1) compact header: "Aninda Payu" in bold grotesque display type (Bricolage Grotesque style) left, small "Keluar" text link right, single blue rule below; (2) dominant focal block: a large ledger day-summary titled "Hari ini" — a two-column ruled table with columns "Masuk" and "Keluar", rows "Transaksi 3 / 5", "Qty 12 / 9", "Nilai Rp 900.000 / Rp 1.250.000", column totals double-underlined in red pencil, the block framed by a 1px ink border with squared 2px corners, no shadow; (3) below: four stamp-style action buttons in a 2x2 grid, each a squared rectangle with 1.5px indigo border and uppercase letterspaced label ("CATAT PENJUALAN", "STOK MASUK", "STOCK OPNAME", "LAPORAN"), like rubber-stamp marks, flat, no shadow; (4) "Stok menipis" ruled list with red pencil entries "Kemeja Malaman M01 — 2 pcs"; (5) fixed bottom nav: five text labels "Stok Transaksi Opname Laporan Pengaturan" with active "Stok" in indigo with soga underline stroke. Zero gradients, zero shadows, zero glass, zero icons, tabular numerals, body text Public Sans style, crisp realistic app UI screenshot.`,
  'comp-3-tab.png': `Flat high-fidelity mobile app UI screenshot, portrait phone viewport, NO device frame. Home screen ("Beranda") of Indonesian batik shop stock-ledger app "Aninda Payu", ledger-book (buku kas) visual world: bone paper #F4F1E9 ground, ink #1C2B36 text, pale blue ruling #B9CFDF, indigo #24518E primary, soga brown #9C4A1F accent, red pencil #B3372B negatives. Dense tool-first composition top to bottom: (1) slim header row: "Aninda Payu" bold grotesque display (Bricolage Grotesque style) with thin double rule beneath, right side small tabular "128 pcs"; (2) horizontal scrollable category tabs like index-card divider tabs for batik types: "malaman", "colet", "babar pindo", "embos", "babar 1" — squared tabs with 1px ink border, active tab filled indigo with paper-color text; (3) below tabs a compact ruled stock list for active category: rows "Kemeja Malaman M01  12 pcs  Rp 900.000", "Kemeja Malaman M02  8 pcs  Rp 760.000" with blue ruling lines, one row value in red pencil "2 pcs" for low stock; (4) a single full-width primary action bar fixed above bottom nav: indigo #24518E rectangle, squared corners, paper-color uppercase letterspaced label "CATAT PENJUALAN"; (5) fixed bottom nav with five text items "Stok Transaksi Opname Laporan Pengaturan", active underlined with soga stroke. Flat: no shadows, no gradients, no glass, no icons, 1px borders #D8D2C4, 2px radii, tabular numerals, Public Sans style body, realistic crisp app screenshot.`,
};

for (const [file, prompt] of Object.entries(prompts)) {
  const res = spawnSync('node', [EMBED, path.join(dir, file), '--prompt', prompt], {
    stdio: 'inherit',
  });
  if (res.status !== 0) process.exit(res.status ?? 1);
  writeFileSync(
    path.join(dir, file.replace(/\.png$/, '.json')),
    JSON.stringify({ prompt, approved: file === 'comp-1-buku-kas.png' }, null, 2),
  );
}
console.log('Provenance tertanam di 3 comp.');
